# Obter a lista de usuários
GET http://localhost:3000/api/compras
Content-Type: application/json
###

# Inserir novo usuário
POST http://localhost:3000/api/compras
Content-Type: application/json

{ 
 "codBarra": 777777, 
 "nome": "Feijaoo", 
 "preco": 18.919,
 "qtd": 23,
 "dataHora": "2022-04-22T22:15:25.000Z"
}
###

# Alterar colaborador
PUT http://localhost:3000/api/compras
Content-Type: application/json

{ 
 "_id": "62672565b3d0c0be66abf918",
 "codBarra": 222, 
 "nome": "Feijão", 
 "preco": 22.59,
 "qtd": 10,
 "dataHora": "2022-04-22T22:15:25.000Z"
}
###

# Excluir um colaborador
DELETE http://localhost:3000/api/compras/626b5e6d05ed95b88107bec0
Content-Type: application/json
###

# Obter pelo id de colaborador
GET http://localhost:3000/api/compras/62672565b3d0c0be66abf918
Content-Type: application/json
###

# Obter colaborador filtrando
GET http://localhost:3000/api/compras/filtro/Fei
Content-Type: application/json
###